name: Downloading Latest APK

on:
  workflow_dispatch:
    inputs:
      region:
        description: "Game server region"
        default: "JP"
        type: choice
        required: true
        options:
          - "JP"
          - "NA"
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.10.4]

    steps:
      - name: Getting files from Repo
        uses: actions/checkout@v2

      - name: Install protoc
        run: python install_protoc.py

      - name: Install GooglePlay-Api depends & reinstall protobuf
        run: |
          pip install -r libs/googleplay-api/requirements.txt
          pip install --force-reinstall protobuf

      - name: Build GooglePlay-Api
        run: |
          cd libs/googleplay-api
          python setup.py build
          cd ../../

      - name: Download JP 32 & 64 Bits
        run: |
          python libs/googleplay-api/downloader.py -e ${{ secrets.GPLAY_EMAIL }} -p ${{ secrets.GPLAY_PASS }} -r ${{ inputs.region }} -t 32
          python libs/googleplay-api/downloader.py -e ${{ secrets.GPLAY_EMAIL }} -p ${{ secrets.GPLAY_PASS }} -r ${{ inputs.region }} -t 64
          
      - name: Upload apk as artifacts
        uses: nanoufo/action-upload-artifacts-and-release-assets@v1.8
        with:
          if-no-files-found: "error"
          path: |
            *.apk
      - name: Send files to Discord
        run: python send_discord.py --discord ${{ secrets.WEBHOOK_URL }}